In [1]:
import numpy as np

In [111]:
a = np.arange(0, 10)
b = np.arange(0,20).reshape(2,10)
c=np.arange(0,10)[None,:]

In [108]:
func = lambda x:  np.where(x[0] >5 , x[0]*10,0)
print(
    f'{a} \n ********* \n {func(a)}'
)

[0 1 2 3 4 5 6 7 8 9] 
 ********* 
 0


In [104]:
func2 = lambda x: np.where(x>5)
print(
    f'{a} \n ********* \n {func2(a)}'
)

[0 1 2 3 4 5 6 7 8 9] (array([6, 7, 8, 9], dtype=int64),)


In [112]:
func = lambda x:  np.where(x[0] >5 , x[0]*10,0)
print(
    f'{c} \n ********* \n {func(c)}'
)

[[0 1 2 3 4 5 6 7 8 9]] 
 ********* 
 [ 0  0  0  0  0  0 60 70 80 90]
