In [1]:
import numpy as np
import sympy as sm

In [2]:
class Infix:
    def __init__(self, function):
        self.function = function
    def __ror__(self, other):
        return Infix(lambda x, self=self, other=other: self.function(other, x))
    def __or__(self, other):
        return self.function(other)
    # def __rlshift__(self, other):
    #     return Infix(lambda x, self=self, other=other: self.function(other, x))
    # def __rshift__(self, other):
    #     return self.function(other)
    def __call__(self, value1, value2):
        return self.function(value1, value2)

In [3]:
def err(f):
    def dec(*args):
        try:
            a = f(args)
        except: print('error')
        else: 
            print('OK')
            return a
        finally: print('Finale')
        
    return dec
    

In [4]:
a_m = np.array(
    [[ 0.0,  1.0,  2.0],
    [10.0, 11.0, 12.0],
    [20.0, 21.0, 22.0],
    [30.0, 31.0, 32.0]]
    )
b_v = np.array([1.0, 2.0, 3.0])
print(b_v)
c_m = b_v.copy()
c_m=c_m[None,:]
print(c_m)
d_m = b_v.copy()
d_m = d_m[:,None]
print(d_m)

[1. 2. 3.]
[[1. 2. 3.]]
[[1.]
 [2.]
 [3.]]


In [18]:
x,y,z,w,a,b,c,d,f,g = sm.symbols('x y z w a b c d f g')

In [55]:
A1 = np.array([[a, b], [c, d]])
b1 = np.array([x, y])
b2 = np.array([z, w])
c1 = np.array([[x], [y]])
c2 = np.array([[z, w]])
print(A1.shape, b1.shape, b1.T.shape, c1.shape)
print(f'{A1} \n{b1} \n{b2} \n{c1} \n{c2}')


(2, 2) (2,) (2,) (2, 1)
[[a b]
 [c d]] 
[x y] 
[z w] 
[[x]
 [y]] 
[[z w]]


In [45]:
print(f'{A1@b1} \n{b1@A1} \n{A1*b1} \n {b1*A1}')

[a*x + b*y c*x + d*y] 
[a*x + c*y b*x + d*y] 
[[a*x b*y]
 [c*x d*y]] 
 [[a*x b*y]
 [c*x d*y]]


In [46]:
print(f'{b1@b2} \n {b2@b1}')

w*y + x*z 
 w*y + x*z


In [56]:
print(f'{c1.T} \n{c2}')

[[x y]] 
[[z w]]


In [47]:
print( f' {b2*c1} \n{c1*b2} \n{b2@c1} \n c1@b2 - error ')

 [[x*z w*x]
 [y*z w*y]] 
[[x*z w*x]
 [y*z w*y]] 
[w*y + x*z] 
 c1@b2 - error 


In [59]:
print( f' {b1*c2} \n{c2*b1} \n{c2@b1} \n b1@c2 - error ')

 [[x*z w*y]] 
[[x*z w*y]] 
[w*y + x*z] 
 b1@c2 - error 


In [60]:
print( f' {c1.T@b2} \n{b1@c2.T}')

 [w*y + x*z] 
[w*y + x*z]
