In [3]:
import numpy as np
import sympy as sm

In [4]:
class Infix:
    def __init__(self, function):
        self.function = function
    def __ror__(self, other):
        return Infix(lambda x, self=self, other=other: self.function(other, x))
    def __or__(self, other):
        return self.function(other)
    # def __rlshift__(self, other):
    #     return Infix(lambda x, self=self, other=other: self.function(other, x))
    # def __rshift__(self, other):
    #     return self.function(other)
    def __call__(self, value1, value2):
        return self.function(value1, value2)

In [5]:
def err(f):
    def dec(*args):
        try:
            a = f(args)
        except: print('error')
        else: 
            print('OK')
            return a
        finally: print('Finale')
        
    return dec
    

In [6]:
a_m = np.array(
    [[ 0.0,  1.0,  2.0],
    [10.0, 11.0, 12.0],
    [20.0, 21.0, 22.0],
    [30.0, 31.0, 32.0]]
    )
b_v = np.array([1.0, 2.0, 3.0])
print(b_v)
c_m = b_v.copy()
c_m=c_m[None,:]
print(c_m)
d_m = b_v.copy()
d_m = d_m[:,None]
print(d_m)

[1. 2. 3.]
[[1. 2. 3.]]
[[1.]
 [2.]
 [3.]]


In [7]:
a_m+b_v

array([[ 1.,  3.,  5.],
       [11., 13., 15.],
       [21., 23., 25.],
       [31., 33., 35.]])

In [8]:
a_m+c_m

array([[ 1.,  3.,  5.],
       [11., 13., 15.],
       [21., 23., 25.],
       [31., 33., 35.]])

In [9]:

try:
    print(a_m+ d_m)
except: print('error')
else: print('OK')
finally: print('Finale')

error
Finale


In [10]:
pr=err(print)

In [11]:
pr(102)

(102,)
OK
Finale


In [12]:
try:
    print(c_m@c_m)
except: print('error')
else: print('OK')
finally: print('Try another path')


error
Try another path


In [13]:
x,y,z,w,a,b,c,d = sm.symbols('x y z w a b c d')

In [14]:
A1 = np.array([[1, 2], [8, 9]])
b1 = np.array([a, b])
b2= np.array([c,d])
c1 = np.array([[x], [y]])

In [15]:
A1@b1

array([a + 2*b, 8*a + 9*b], dtype=object)

In [16]:
b1@A1

array([a + 8*b, 2*a + 9*b], dtype=object)

In [17]:
A1@c1

array([[x + 2*y],
       [8*x + 9*y]], dtype=object)

In [18]:
c1.T@A1

array([[x + 8*y, 2*x + 9*y]], dtype=object)

In [19]:
b1@A1

array([a + 8*b, 2*a + 9*b], dtype=object)

In [20]:
A1@c1

array([[x + 2*y],
       [8*x + 9*y]], dtype=object)

In [21]:
c1.T@A1

array([[x + 8*y, 2*x + 9*y]], dtype=object)

In [22]:
A1 * [1,2]

array([[ 1,  4],
       [ 8, 18]])

In [23]:
b1@c1

array([a*x + b*y], dtype=object)

In [24]:
c1@b1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [25]:
b1@b2

a*c + b*d

In [26]:
b2@b1

a*c + b*d

In [27]:
c1@b1.T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [28]:
b1.T@c1

array([a*x + b*y], dtype=object)

In [29]:
b1.T==b1

array([ True,  True])

In [30]:
print(b1.ndim)
print(c1.ndim)

1
2


In [31]:
print(c1)
print(c1.T)

[[x]
 [y]]
[[x y]]


In [32]:
def res ():
    return np.sin(a)/a**100

In [37]:
a =10000

res()

OverflowError: int too large to convert to float